
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('interview').del()
    .then(function () {
      // Inserts seed entries
      return knex('interview').insert([
        {id: 1, title: 'My presure!', content: "Once in a while I tend to put down the books I'm reading and surf around on the internet. Most of the time I type in some phrases like 'Tolkien type signed letter' or 'Tolkien ALS' to track down letters to add to my collection of transcripts I'm building. Today I accidentally bumped into a recording of Tolkien from 1964 on YouTube. I don't know what the BBC thinks of this, or if it is legal to publish it at all, still it is very interesting. In 1964 Tolkien was interviewed by Irene Slade for the programme 'Reluctant Olympians' in the British Broadcasting Corporation's radio series 'A World of Sound', and informally (with a midget tape recorderd) by Denys Geroult for the BBC Sound Archives (now the National Sound Archives). The second interview is the one I found on Youtube. Dennis Gueroult from the BBC Radio 4 program 'Now Read On', who in many ways manages to ask a lot of fine questions and provokes even more interesting answers, did broadcast this interview for the first time in 1971 (more then 7 years later). It was a nice find, and although there is just the voices and no moving images, it still touches my imagination. You can hear, if you listen carefully how Tolkien sometimes ticks his pipe, or talks with the pipe in between his teeth, or even searches for matches. I also have the impression that at first he is still a bit nervous, but then later on in the conversation eases up a lot and speaks straight from the heart about Hobbits, England, and so on. It is wonderful to hear the professor talk, and sometimes even mumble or openly laugh. I have tried to type down a transcript of the interview and hope you can enjoy the recording even more by using it.", interviewer: "Davide Avanzi", id_book: 1},
        {id: 2, title: 'The angry robot!', content: "When his autobiography In Joy Still Felt appeared in 1980, Isaac Asimov could count over 200 books published in the three decades since his first novel, Pebble in the Sky (1950), was printed. In addition he has published more stories and essays than even a man of his prodigious energy has gotten around to counting. One of them, 'The Prolific Writer, which originally appeared in the October 1979 issue of The Writer, examines the mixed blessings of such prolificity. To be prolific, he warns, one must be a 'singleminded, driven, nonstop person.' Surveying the list of Asimov's publications, one is struck by the range of his writing, from scores of books on mathematics and the sciences (he holds a PhD in chemistry from Columbia) through studies of history and guides to the Bible and Shakespeare. If his name has become a household term, however, it is because of his SF: his Foundation trilogy, along with Arthur Clarke's 2001 and Robert Heinlein's Stranger in a Strange Land, is unquestionably one of the seminal works of American SF. What follows is largely a transcript of a conversation that took place on October 20, 1976, during a visit by Asimov to the State University of New York College at Brockport. The other participants were area writers Gregory Fitz Gerald and Jack Wolf and an undergraduate student, Joshua Duberman. To their questions Robert Philmus has added one other, in his obliging response to which Asimov refers to his most recent work. ", interviewer: "Fabrizio Carsenzuola", id_book: 4},
        {id: 3, title: 'A horror story!', content: "If Ray Bradbury is the reigning King of the literature of the fantastic, then Stephen King is the heir apparent to the throne. Among King’s works are the immensely popular ’Salem’s Lot, Carrie, The Shining, and a collection of short stories entitled Night Shift. Carrie, of course, became Brian De Palma’s spectacular film, while Kubrick is currently filming The Shining. Several of the stories in Night Shift will soon be adapted to the screen in not one, but two separate productions. In this exclusive interview, Stephen King discusses his past work, his inspirations, his attitudes toward the genre, and his future projects.", interviewer: "Stefano Farina", id_book: 6},
        {id: 4, title: 'W Voldemort', content: "It’s been more than five years since J.K. Rowling’s final Harry Potter book was released. But it doesn’t mean the wizarding world has come to a halt. 2014 brought columns from Rita Skeeter, social media riddles from Rowling and revelations that Hogwarts was as warm and welcoming a place to diversity as Potter fans would have wanted. Though some critics argue Rowling needs to cool it with the new content, Potter fanatics feel otherwise. Here’s everything we learned about the wizarding world in 2014. Dumbledore’s Army members are in their thirties. Rowling hit the heart of nostalgia in July when she published a gossip column from Rita Skeeter about Harry and Company’s reunion at the Quidditch World Cup. The infamous wizards, “no longer the fresh-faced teenagers they were in their heyday,” are now in their thirties. Harry, a 34-year-old with “threads of silver” in his hair, was sporting a new scar, a “nasty cut over his right cheekbone,” which Skeeter speculated was from an argument with his wife Ginny Potter, now a reporter for the Daily Prophet.", interviewer: "Marianna Felt", id_book: 9}      ]);
    });
};
